# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 586)
        MainWindow.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(157, 0, 0);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(157, 0, 0);\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(157, 0, 0);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* HORIZONTAL SCROLLBAR - HOMEWORK */\n"
"QScrollBar:horizontal {\n"
"   \n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: black;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(56, 56, 85);\n"
" }")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -691, 681, 1218))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(600, 1200))
        self.frame.setStyleSheet("background-color: rgb(90, 90, 90);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(-20, -10, 751, 91))
        self.label_4.setStyleSheet("background-color: black;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QPushButton#searchButton {\n"
"    padding: 10px 20px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton#searchButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"QPushButton#searchButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"QPushButton#searchButton:focus {\n"
"    outline: none;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(-30, 80, 770, 31))
        self.label_14.setStyleSheet("background-color: red")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 110, 671, 1091))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.FILM1 = QtWidgets.QLabel(self.frame)
        self.FILM1.setGeometry(QtCore.QRect(60, 640, 131, 181))
        self.FILM1.setText("")
        self.FILM1.setPixmap(QtGui.QPixmap(":/images/film1.png"))
        self.FILM1.setScaledContents(True)
        self.FILM1.setAlignment(QtCore.Qt.AlignCenter)
        self.FILM1.setObjectName("FILM1")
        self.ABU1 = QtWidgets.QLabel(self.frame)
        self.ABU1.setGeometry(QtCore.QRect(30, 140, 600, 741))
        self.ABU1.setAutoFillBackground(False)
        self.ABU1.setStyleSheet("background-color: rgba(255, 255, 255, 0.2);\n"
"color: rgb(170, 0, 0);\n"
"    color: #000000;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    border-radius: 10px;")
        self.ABU1.setText("")
        self.ABU1.setObjectName("ABU1")
        self.GARIS_6 = QtWidgets.QLabel(self.frame)
        self.GARIS_6.setGeometry(QtCore.QRect(-60, 956, 751, 5))
        self.GARIS_6.setAutoFillBackground(False)
        self.GARIS_6.setStyleSheet("background-color: red;\n"
"    border-radius: 10px;\n"
"    padding: 5px;")
        self.GARIS_6.setText("")
        self.GARIS_6.setObjectName("GARIS_6")
        self.CR = QtWidgets.QLabel(self.frame)
        self.CR.setGeometry(QtCore.QRect(0, 1140, 641, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.CR.setFont(font)
        self.CR.setStyleSheet("color: white; background-color: rgba(0, 0, 0, 0);\n"
"")
        self.CR.setAlignment(QtCore.Qt.AlignCenter)
        self.CR.setObjectName("CR")
        self.DESK = QtWidgets.QLabel(self.frame)
        self.DESK.setGeometry(QtCore.QRect(10, 990, 641, 141))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DESK.setFont(font)
        self.DESK.setStyleSheet("color: white; background-color: rgba(0, 0, 0, 0);\n"
"")
        self.DESK.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DESK.setWordWrap(False)
        self.DESK.setObjectName("DESK")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(40, 85, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAutoFillBackground(False)
        self.label_20.setStyleSheet("color: white;background-color: rgba(0, 0, 0, 0);")
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(160, 85, 61, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("color: white;background-color: rgba(0, 0, 0, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(423, 85, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAutoFillBackground(False)
        self.label_21.setStyleSheet("color: white;background-color: rgba(0, 0, 0, 0);")
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(530, 85, 101, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setAutoFillBackground(False)
        self.label_22.setStyleSheet("color: white;background-color: rgba(0, 0, 0, 0);")
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(290, 85, 81, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("color: white;background-color: rgba(0, 0, 0, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.LOGOUT_2 = QtWidgets.QPushButton(self.frame)
        self.LOGOUT_2.setGeometry(QtCore.QRect(625, 25, 30, 25))
        self.LOGOUT_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.LOGOUT_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LOGOUT_2.setIcon(icon)
        self.LOGOUT_2.setIconSize(QtCore.QSize(20, 20))
        self.LOGOUT_2.setObjectName("LOGOUT_2")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(371, 28, 25, 15))
        self.label_17.setStyleSheet("color: white;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/images/faq.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.FAQ_7 = QtWidgets.QLabel(self.frame)
        self.FAQ_7.setGeometry(QtCore.QRect(470, 23, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.FAQ_7.setFont(font)
        self.FAQ_7.setAutoFillBackground(False)
        self.FAQ_7.setStyleSheet("color: white;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"")
        self.FAQ_7.setObjectName("FAQ_7")
        self.FAQ_6 = QtWidgets.QLabel(self.frame)
        self.FAQ_6.setGeometry(QtCore.QRect(550, 23, 71, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.FAQ_6.setFont(font)
        self.FAQ_6.setAutoFillBackground(False)
        self.FAQ_6.setStyleSheet("color: white;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"")
        self.FAQ_6.setObjectName("FAQ_6")
        self.FAQ_5 = QtWidgets.QLabel(self.frame)
        self.FAQ_5.setGeometry(QtCore.QRect(401, 22, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.FAQ_5.setFont(font)
        self.FAQ_5.setAutoFillBackground(False)
        self.FAQ_5.setStyleSheet("color: white;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"")
        self.FAQ_5.setObjectName("FAQ_5")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(444, 27, 24, 16))
        self.label_18.setStyleSheet("color: white;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"")
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/images/gembok.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(522, 29, 25, 15))
        self.label_19.setStyleSheet("color: white;\n"
"background-color: rgba(0, 0, 0, 0);\n"
"")
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/images/list.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.Judul = QtWidgets.QLabel(self.frame)
        self.Judul.setGeometry(QtCore.QRect(220, 645, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Judul.setFont(font)
        self.Judul.setStyleSheet("color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);background-color: rgba(0, 0, 0, 0);")
        self.Judul.setObjectName("Judul")
        self.FILM2 = QtWidgets.QLabel(self.frame)
        self.FILM2.setGeometry(QtCore.QRect(60, 230, 531, 361))
        self.FILM2.setText("")
        self.FILM2.setPixmap(QtGui.QPixmap(":/images/film1.png"))
        self.FILM2.setScaledContents(True)
        self.FILM2.setAlignment(QtCore.Qt.AlignCenter)
        self.FILM2.setObjectName("FILM2")
        self.Pemberitahuan = QtWidgets.QLabel(self.frame)
        self.Pemberitahuan.setGeometry(QtCore.QRect(130, 180, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Pemberitahuan.setFont(font)
        self.Pemberitahuan.setStyleSheet("color: rgb(170, 0, 0);background-color: rgba(0, 0, 0, 0);\n"
"")
        self.Pemberitahuan.setAlignment(QtCore.Qt.AlignCenter)
        self.Pemberitahuan.setObjectName("Pemberitahuan")
        self.Sinopsis = QtWidgets.QLabel(self.frame)
        self.Sinopsis.setGeometry(QtCore.QRect(220, 680, 291, 16))
        self.Sinopsis.setStyleSheet("color: rgb(255, 255, 255);background-color: rgba(0, 0, 0, 0);")
        self.Sinopsis.setObjectName("Sinopsis")
        self.tgl_rilis = QtWidgets.QLabel(self.frame)
        self.tgl_rilis.setGeometry(QtCore.QRect(220, 710, 81, 16))
        self.tgl_rilis.setStyleSheet("color: rgb(255, 255, 255);background-color: rgba(0, 0, 0, 0);")
        self.tgl_rilis.setObjectName("tgl_rilis")
        self.asal_FILM = QtWidgets.QLabel(self.frame)
        self.asal_FILM.setGeometry(QtCore.QRect(310, 710, 41, 16))
        self.asal_FILM.setStyleSheet("color: rgb(255, 255, 255);background-color: rgba(0, 0, 0, 0);")
        self.asal_FILM.setObjectName("asal_FILM")
        self.Durasi = QtWidgets.QLabel(self.frame)
        self.Durasi.setGeometry(QtCore.QRect(360, 710, 51, 16))
        self.Durasi.setStyleSheet("color: rgb(255, 255, 255);background-color: rgba(0, 0, 0, 0);")
        self.Durasi.setObjectName("Durasi")
        self.Rating = QtWidgets.QLabel(self.frame)
        self.Rating.setGeometry(QtCore.QRect(220, 730, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Rating.setFont(font)
        self.Rating.setStyleSheet("color: rgb(255, 255, 255);background-color: rgba(0, 0, 0, 0);")
        self.Rating.setObjectName("Rating")
        self.genre1 = QtWidgets.QLabel(self.frame)
        self.genre1.setGeometry(QtCore.QRect(220, 770, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.genre1.setFont(font)
        self.genre1.setStyleSheet("color: rgb(255, 255, 255);background-color: rgba(0, 0, 0, 0);")
        self.genre1.setObjectName("genre1")
        self.genre2 = QtWidgets.QLabel(self.frame)
        self.genre2.setGeometry(QtCore.QRect(280, 770, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.genre2.setFont(font)
        self.genre2.setStyleSheet("color: rgb(255, 255, 255);background-color: rgba(0, 0, 0, 0);")
        self.genre2.setObjectName("genre2")
        self.genre3 = QtWidgets.QLabel(self.frame)
        self.genre3.setGeometry(QtCore.QRect(360, 770, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.genre3.setFont(font)
        self.genre3.setStyleSheet("color: rgb(255, 255, 255);background-color: rgba(0, 0, 0, 0);")
        self.genre3.setObjectName("genre3")
        self.genre4 = QtWidgets.QLabel(self.frame)
        self.genre4.setGeometry(QtCore.QRect(440, 770, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.genre4.setFont(font)
        self.genre4.setStyleSheet("color: rgb(255, 255, 255);background-color: rgba(0, 0, 0, 0);")
        self.genre4.setObjectName("genre4")
        self.user = QtWidgets.QLabel(self.frame)
        self.user.setGeometry(QtCore.QRect(280, 740, 16, 21))
        self.user.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.user.setText("")
        self.user.setPixmap(QtGui.QPixmap(":/images/user.png"))
        self.user.setScaledContents(True)
        self.user.setAlignment(QtCore.Qt.AlignCenter)
        self.user.setObjectName("user")
        self.view = QtWidgets.QLabel(self.frame)
        self.view.setGeometry(QtCore.QRect(300, 745, 81, 21))
        self.view.setStyleSheet("color: rgb(255, 255, 255);background-color: rgba(0, 0, 0, 0);")
        self.view.setObjectName("view")
        self.play_button1 = QtWidgets.QPushButton(self.frame)
        self.play_button1.setGeometry(QtCore.QRect(290, 350, 71, 71))
        self.play_button1.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.play_button1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/play button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button1.setIcon(icon1)
        self.play_button1.setIconSize(QtCore.QSize(40, 40))
        self.play_button1.setObjectName("play_button1")
        self.Durasi2 = QtWidgets.QLabel(self.frame)
        self.Durasi2.setGeometry(QtCore.QRect(80, 560, 490, 5))
        self.Durasi2.setStyleSheet("background-color: rgb(136, 136, 136);")
        self.Durasi2.setText("")
        self.Durasi2.setObjectName("Durasi2")
        self.play_button2 = QtWidgets.QPushButton(self.frame)
        self.play_button2.setGeometry(QtCore.QRect(80, 570, 16, 16))
        self.play_button2.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.play_button2.setText("")
        self.play_button2.setIcon(icon1)
        self.play_button2.setObjectName("play_button2")
        self.rewind1 = QtWidgets.QPushButton(self.frame)
        self.rewind1.setGeometry(QtCore.QRect(100, 570, 16, 16))
        self.rewind1.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.rewind1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/Rewind2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewind1.setIcon(icon2)
        self.rewind1.setObjectName("rewind1")
        self.sound = QtWidgets.QPushButton(self.frame)
        self.sound.setGeometry(QtCore.QRect(140, 570, 16, 16))
        self.sound.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.sound.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/sound logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sound.setIcon(icon3)
        self.sound.setObjectName("sound")
        self.rewind2 = QtWidgets.QPushButton(self.frame)
        self.rewind2.setGeometry(QtCore.QRect(120, 570, 16, 16))
        self.rewind2.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.rewind2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/rewind 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewind2.setIcon(icon4)
        self.rewind2.setObjectName("rewind2")
        self.pengaturan = QtWidgets.QPushButton(self.frame)
        self.pengaturan.setGeometry(QtCore.QRect(530, 570, 16, 16))
        self.pengaturan.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pengaturan.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/pengaturan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pengaturan.setIcon(icon5)
        self.pengaturan.setObjectName("pengaturan")
        self.cc = QtWidgets.QPushButton(self.frame)
        self.cc.setGeometry(QtCore.QRect(510, 570, 16, 16))
        self.cc.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.cc.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/cc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cc.setIcon(icon6)
        self.cc.setObjectName("cc")
        self.fullscreen = QtWidgets.QPushButton(self.frame)
        self.fullscreen.setGeometry(QtCore.QRect(550, 570, 16, 16))
        self.fullscreen.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.fullscreen.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/fullscreen_icon_160080.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fullscreen.setIcon(icon7)
        self.fullscreen.setObjectName("fullscreen")
        self.LOGO_3 = QtWidgets.QPushButton(self.frame)
        self.LOGO_3.setGeometry(QtCore.QRect(1, -10, 111, 91))
        self.LOGO_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"")
        self.LOGO_3.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LOGO_3.setIcon(icon8)
        self.LOGO_3.setIconSize(QtCore.QSize(100, 100))
        self.LOGO_3.setObjectName("LOGO_3")
        self.label_14.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.lineEdit_2.raise_()
        self.ABU1.raise_()
        self.FILM1.raise_()
        self.GARIS_6.raise_()
        self.CR.raise_()
        self.DESK.raise_()
        self.label_20.raise_()
        self.label_7.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_8.raise_()
        self.LOGOUT_2.raise_()
        self.label_17.raise_()
        self.FAQ_7.raise_()
        self.FAQ_6.raise_()
        self.FAQ_5.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.Judul.raise_()
        self.FILM2.raise_()
        self.Pemberitahuan.raise_()
        self.Sinopsis.raise_()
        self.tgl_rilis.raise_()
        self.asal_FILM.raise_()
        self.Durasi.raise_()
        self.Rating.raise_()
        self.genre1.raise_()
        self.genre2.raise_()
        self.genre3.raise_()
        self.genre4.raise_()
        self.user.raise_()
        self.view.raise_()
        self.play_button1.raise_()
        self.Durasi2.raise_()
        self.play_button2.raise_()
        self.rewind1.raise_()
        self.sound.raise_()
        self.rewind2.raise_()
        self.pengaturan.raise_()
        self.cc.raise_()
        self.fullscreen.raise_()
        self.LOGO_3.raise_()
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "  Search Movies"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.CR.setText(_translate("MainWindow", "Copyright @2021 YOUPET - All Rights Reserved Disclaimer: This site does not store any files\n"
" on its server. All contents are provided by non-affiliated third parties and make money online"))
        self.DESK.setText(_translate("MainWindow", "YOUPET Streaming Film dan TV Series Subtitle Indonesia\n"
"YOUPET adalah situs web nonton streaming online download film terbaru film asia\n"
"terbaru, film barat terbaru secara gratis dan lengkap. Disini tersedia banyak\n"
"kualitas video seperti bluray, web-dl, hd, dvdrip, hdrip dan hdcam. Format video\n"
"yang kami sediakan ada mp4 mkv serta berbagai macam resolusi seperti 360p, 480p,\n"
"720p dan 1080p. Semua film yang tersedia di situs ini hanya untuk review saja.\n"
"Jika anda ingin menonton filmdengan kualitas yang lebih baik, silahkan beli DVD\n"
"resminya."))
        self.label_20.setText(_translate("MainWindow", "HOME"))
        self.label_7.setText(_translate("MainWindow", "GENRE"))
        self.label_21.setText(_translate("MainWindow", "YEAR"))
        self.label_22.setText(_translate("MainWindow", "BOX OFFICE"))
        self.label_8.setText(_translate("MainWindow", "COUNTRY"))
        self.FAQ_7.setText(_translate("MainWindow", "DMCA"))
        self.FAQ_6.setText(_translate("MainWindow", "SITEMAP"))
        self.FAQ_5.setText(_translate("MainWindow", "FAQ"))
        self.Judul.setText(_translate("MainWindow", "Black Clover: Sword of the Wizard King (2023)"))
        self.Pemberitahuan.setText(_translate("MainWindow", "Jika mengalami error atau gangguan baca Bantuan untuk lebih lanjut.\n"
"Diskusi Film/Series maupun Request atau Komplain ke IG YOUPET"))
        self.Sinopsis.setText(_translate("MainWindow", "When the legend revives... The kingdom will fall."))
        self.tgl_rilis.setText(_translate("MainWindow", "16. Jun, 2023"))
        self.asal_FILM.setText(_translate("MainWindow", "JAPAN"))
        self.Durasi.setText(_translate("MainWindow", "113Min."))
        self.Rating.setText(_translate("MainWindow", "9.6"))
        self.genre1.setText(_translate("MainWindow", "Action"))
        self.genre2.setText(_translate("MainWindow", "Adventure"))
        self.genre3.setText(_translate("MainWindow", "Animation"))
        self.genre4.setText(_translate("MainWindow", "Fantasy"))
        self.view.setText(_translate("MainWindow", "263119 Views"))
import res_rc
