# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_REGISTERR(object):
    def setupUi(self, REGISTERR):
        REGISTERR.setObjectName("REGISTERR")
        REGISTERR.resize(625, 565)
        self.widget = QtWidgets.QWidget(REGISTERR)
        self.widget.setGeometry(QtCore.QRect(30, 30, 550, 500))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(250, 380, 261, 81))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("border-image: url(:/images/background1.png);\n"
"border-bottom-right-radius: 50 px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/background1.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 221, 430))
        self.label_2.setStyleSheet("border-top-left-radius: 50px;\n"
"background-color:rgba(0, 0, 0, 80);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(330, 80, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.label_4.setObjectName("label_4")
        self.USERNAME = QtWidgets.QLineEdit(self.widget)
        self.USERNAME.setGeometry(QtCore.QRect(279, 220, 211, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.USERNAME.setFont(font)
        self.USERNAME.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.USERNAME.setObjectName("USERNAME")
        self.PASSWORD = QtWidgets.QLineEdit(self.widget)
        self.PASSWORD.setGeometry(QtCore.QRect(279, 270, 211, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PASSWORD.setFont(font)
        self.PASSWORD.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.PASSWORD.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PASSWORD.setObjectName("PASSWORD")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(281, 410, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(0, 0, 0, 210);")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(50, 80, 201, 40))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgba(255, 255, 255, 200);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(50, 125, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgba(255, 255, 255, 170);")
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(260, 30, 251, 430))
        self.label_3.setStyleSheet("background-color:rgba(255, 255, 255, 255);\n"
"border-bottom-right-radius: 50px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(260, 30, 251, 101))
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet(";\n"
"border-image: url(:/images/background3.png);\n"
"border-bottom-right-radius: 100 px;")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/images/background3.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(260, 60, 251, 141))
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("border-image: url(:/images/background2.png);\n"
"border-bottom-right-radius: 100 px;")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/images/background2.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(40, 30, 221, 431))
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet("border-image: url(:/images/asta.jpg);\n"
"border-bottom-right-radius: 100 px;")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/images/asta.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.LOGIN = QtWidgets.QPushButton(self.widget)
        self.LOGIN.setGeometry(QtCore.QRect(378, 409, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LOGIN.setFont(font)
        self.LOGIN.setStyleSheet("color: blue;background-color: rgba(0, 0, 0, 0);\n"
"")
        self.LOGIN.setObjectName("LOGIN")
        self.FIRSTNAME = QtWidgets.QLineEdit(self.widget)
        self.FIRSTNAME.setGeometry(QtCore.QRect(280, 170, 91, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FIRSTNAME.setFont(font)
        self.FIRSTNAME.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.FIRSTNAME.setObjectName("FIRSTNAME")
        self.LASTNAME = QtWidgets.QLineEdit(self.widget)
        self.LASTNAME.setGeometry(QtCore.QRect(400, 170, 91, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LASTNAME.setFont(font)
        self.LASTNAME.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.LASTNAME.setObjectName("LASTNAME")
        self.REGISTER = QtWidgets.QPushButton(self.widget)
        self.REGISTER.setGeometry(QtCore.QRect(295, 335, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.REGISTER.setFont(font)
        self.REGISTER.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid red;\n"
"    color: red;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.REGISTER.setFlat(True)
        self.REGISTER.setObjectName("REGISTER")
        self.label_3.raise_()
        self.label.raise_()
        self.LOGIN.raise_()
        self.label_5.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.USERNAME.raise_()
        self.PASSWORD.raise_()
        self.FIRSTNAME.raise_()
        self.LASTNAME.raise_()
        self.REGISTER.raise_()
        self.label_2.raise_()

        self.retranslateUi(REGISTERR)
        QtCore.QMetaObject.connectSlotsByName(REGISTERR)

    def retranslateUi(self, REGISTERR):
        _translate = QtCore.QCoreApplication.translate
        REGISTERR.setWindowTitle(_translate("REGISTERR", "Form"))
        self.label_4.setText(_translate("REGISTERR", "Register"))
        self.USERNAME.setPlaceholderText(_translate("REGISTERR", "  User Name"))
        self.PASSWORD.setPlaceholderText(_translate("REGISTERR", "  Password"))
        self.label_5.setText(_translate("REGISTERR", "Already Member?"))
        self.label_7.setText(_translate("REGISTERR", "Project Akhir"))
        self.label_8.setText(_translate("REGISTERR", "Hallo semua,\n"
"Selamat datang di aplikasi \n"
"streaming. Jangan lupa \n"
"di sawer :v."))
        self.LOGIN.setText(_translate("REGISTERR", "Login"))
        self.FIRSTNAME.setPlaceholderText(_translate("REGISTERR", "  First Name"))
        self.LASTNAME.setPlaceholderText(_translate("REGISTERR", "  Last Name"))
        self.REGISTER.setText(_translate("REGISTERR", "R E G I S T E R"))
import res_rc
